codecov:
  branch: develop
  bot: "codecov-io"

comment: false          # don't comment on PRs
github_checks: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%   # don't allow coverage to drop otherwise fail the PR

    patch: off

    # do not run coverage on changes
    # changes: false
