---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: 09:00
      timezone: Europe/Amsterdam
    reviewers: [strickvl]
    labels: [dependencies, internal]
    target-branch: develop
