repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: [--filter-files, --check-only]
        files: \.py$
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--check]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--recursive",
            "-c",
          ]
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: v0.910
  #    hooks:
  #      - id: mypy
  #        additional_dependencies: [apache-airflow~=2.2.0, ml-pipelines-sdk~=1.3.0, apache-beam~=2.30.0, pydantic~=1.8.2,
  #                                  analytics-python~=1.4.0, click~=8.0.1, gitpython~=3.1.18, torch~=1.10.0, types-tabulate, types-croniter,
  #                                  types-futures, types-Markdown, types-protobuf, types-PyMySQL, types-python-dateutil,
  #                                  types-PyYAML, types-requests, types-setuptools, types-six, types-tabulate, types-toml]
  #        args: [  ]
  #        files: ^src/zenml
  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: []
        files: ^src/zenml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: dependency_update_warning
        name: dependency_update_warning
        entry: python -c "print('***WARNING***\nIf any dependency was added/removed/updated, make sure to mirror those changes in .pre-commit-config.yaml!\n')"
        language: system
        verbose: true
        files: pyproject.toml
