steps:
  # login to dockerhub
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-login'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  # build base image
  - name : 'gcr.io/cloud-builders/docker'
    id: 'build-base'
    waitFor: ['docker-login']
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg ZENML_VERSION=$TAG_NAME -t $$USERNAME/zenml:$TAG_NAME -t $$USERNAME/zenml:latest -f docker/base.Dockerfile .']
    secretEnv: ['USERNAME']

  # build CUDA image
  - name : 'gcr.io/cloud-builders/docker'
    id: 'build-cuda'
    waitFor: [ 'docker-login' ]
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg ZENML_VERSION=$TAG_NAME -t $$USERNAME/zenml:$TAG_NAME-cuda -t $$USERNAME/zenml:latest-cuda -f docker/cuda.Dockerfile .']
    secretEnv: ['USERNAME']

  # push the non-development images. this happens early to get the images
  # published as soon as possible after the release to provide the base
  # container image for kubeflow etc.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    entrypoint: 'bash'
    args: [ '-c', 'docker push $$USERNAME/zenml' ]
    secretEnv: [ 'USERNAME' ]

  # build base development image
  - name : 'gcr.io/cloud-builders/docker'
    id: 'build-base-dev'
    waitFor: ['push']
    entrypoint: 'bash'
    args: ['-c', 'docker build -t $$USERNAME/zenml:$TAG_NAME-dev -t $$USERNAME/zenml:latest-dev -f docker/base-dev.Dockerfile .']
    secretEnv: ['USERNAME']

  # build CUDA development image
  - name : 'gcr.io/cloud-builders/docker'
    id: 'build-cuda-dev'
    waitFor: [ 'push' ]
    entrypoint: 'bash'
    args: ['-c', 'docker build -t $$USERNAME/zenml:$TAG_NAME-cuda-dev -t $$USERNAME/zenml:latest-cuda-dev -f docker/cuda-dev.Dockerfile .']
    secretEnv: ['USERNAME']

  # push the development images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-dev'
    entrypoint: 'bash'
    args: [ '-c', 'docker push $$USERNAME/zenml' ]
    secretEnv: [ 'USERNAME' ]


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
      env: 'PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
      env: 'USERNAME'
timeout: 7200s
