# Advanced AWS configurations (optional).
# Apply to all new instances but not existing ones.
aws:
  # Tags to assign to all instances launched by SkyPilot (optional).
  #
  # Example use case: cost tracking by user/team/project.
  #
  # Users should guarantee that these key-values are valid AWS tags, otherwise
  # errors from the cloud provider will be surfaced.
  instance_tags:
    z-env: dev
    z-owner: safoine
    z-project: skypilot