name: hihi
provider: aws
create_rds: true
username: default
password: zenml
email: "i@y.com"
log_level: ERROR
ingress_path: jayesh-server
rds_sslVerifyServerCert: false
create_ingress_controller: false
ingress_controller_hostname: ac8e6c63af207436194ab675ee71d85a-1399000870.us-east-1.elb.amazonaws.com

zenmlserver_namespace: testcli

