settings:
  docker:
   parent_image: safoinext/zenml-dev:step-retry
   python_package_installer: uv

steps:
  my_step:
    enable_cache: False
  step_1:
    enable_cache: False
    # Uncomment and set value to use a step operator for this step
    #step_operator: gcp
    enable_step_logs: False
  step_2:
    enable_cache: False
    # Uncomment and set value to use a step operator for this step
    #step_operator: gcp
    enable_step_logs: False
  step_3:
    enable_cache: False
    # Uncomment and set value to use a step operator for this step
    #step_operator: gcp
    enable_step_logs: False
