{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.generateCerts -}}
{{- $ca := genCA "zenml-ca" 365 }}
{{- $altDns := (list .Values.ingress.host) -}}
{{- if and .Values.zenml.grpcMetadata.enabled .Values.ingress.grpcMetadata.enabled .Values.ingress.tls.grpcMetadata.enabled .Values.ingress.grpcMetadata.host -}}
{{- $altDns = .Values.ingress.grpcMetadata.host | append $altDns -}}
{{- end -}}
{{- $cert := genSignedCert .Values.ingress.host nil $altDns 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
