{{- if and .Values.ingress.enabled .Values.ingress.tls .Values.ingress.tls.generateCerts -}}
{{- $ca := genCA "zenml-ca" 365 }}
{{- if and .Values.zenml.grpcMetadata.enabled .Values.ingress.grpcMetadata.host }}
{{- $altDns := (list .Values.ingress.host .Values.ingress.grpcMetadata.host) }}
{{- else }}
{{- $altDns := (list .Values.ingress.host) }}
{{- end }}
{{- $altDns := (list .Values.ingress.host .Values.ingress.grpcMetadata.host) }}
{{- $cert := genSignedCert .Values.ingress.host nil $altDns 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
