{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.generateCerts -}}
{{- $ca := genCA "zenml-ca" 365 -}}
{{- $altDns := (list .Values.ingress.host) -}}
{{- if and .Values.zenml.grpcMetadata.enabled .Values.ingress.grpcMetadata.enabled .Values.ingress.grpcMetadata.tls.enabled .Values.ingress.grpcMetadata.host -}}
{{- $altDns = .Values.ingress.grpcMetadata.host | append $altDns -}}
{{- end -}}
{{- $serverCert := genSignedCert .Values.ingress.host nil $altDns 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  tls.crt: {{ $serverCert.Cert | b64enc | quote }}
  tls.key: {{ $serverCert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  {{- if and .Values.zenml.grpcMetadata.enabled .Values.ingress.grpcMetadata.enabled .Values.ingress.grpcMetadata.tls.enabled }}
  client.crt: {{ $clientCert.Cert | b64enc | quote }}
  client.key: {{ $clientCert.Key | b64enc | quote }}
  {{- end }}
---
{{- if and .Values.zenml.grpcMetadata.enabled .Values.ingress.grpcMetadata.enabled .Values.ingress.grpcMetadata.tls.enabled -}}
{{- $clientCert := genSignedCert "" nil nil 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.grpcMetadata.secretName }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  tls.crt: {{ $clientCert.Cert | b64enc | quote }}
  tls.key: {{ $clientCert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end -}}
{{- end }}
