{{- if and .Values.zenml.grpcMetadata.enabled .Values.zenml.database.url }}
{{- $partsOne := split "/" .Values.zenml.database.url }}
{{- $database := $partsOne._3 }}
{{- $partsTwo := split "@" $partsOne._2 }}
{{- $partsThree := split ":" $partsTwo._0 }}
{{- $user := $partsThree._0 }}
{{- $password := $partsThree._1 }}
{{- $partsFour := split ":" $partsTwo._1 }}
{{- $host := $partsFour._0 }}
{{- $port := $partsFour._1 }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "zenml.fullname" . }}-grpc-metadata
  labels:
    {{- include "zenml.metadataLabels" . | nindent 4 }}
stringData:
  metadata-store-config.pb: |
    connection_config {
      mysql {
        host: '{{ $host }}'
        port: {{ $port | default 3306 }}
        database: '{{ $database }}'
        user: '{{ $user }}'
        password: '{{ $password }}'
        ssl_options {
          {{- if .Values.zenml.database.sslCa }}
          ca: '/certs/server-ca.pem'
          {{- end }}
          {{- if .Values.zenml.database.sslCert }}
          cert: '/certs/client-cert.pem'
          {{- end }}
          {{- if .Values.zenml.database.sslKey }}
          key: '/certs/client-key.pem'
          {{- end }}
          verify_server_cert: false
        }
        skip_db_creation: false
      }
    }
    migration_options {
      enable_upgrade_migration: true
    }
{{- end }}
