{{- if and .Values.ingress.enabled .Values.zenml.grpcMetadata.enabled .Values.ingress.grpcMetadata.enabled .Values.zenml.database.url -}}
{{- $fullName := include "zenml.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc-metadata
  labels:
    {{- include "zenml.metadataLabels" . | nindent 4 }}
  {{- with .Values.ingress.grpcMetadata.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.grpcMetadata.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.grpcMetadata.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-grpc-metadata
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-grpc-metadata
              servicePort: {{ $svcPort }}
              {{- end }}
      {{- if .Values.ingress.grpcMetadata.host }}
      host: {{ .Values.ingress.grpcMetadata.host | quote }}
      {{- end }}
{{- end }}
