apiVersion: v2
name: zenml
<<<<<<< Updated upstream
version: "0.54.1"
=======
version: "0.54.0-dev153"
>>>>>>> Stashed changes
description: Open source MLOps framework for portable production ready ML pipelines
keywords:
- mlops
- zenml
- server
home: https://zenml.io
sources:
- https://github.com/zenml-io/zenml
icon: https://raw.githubusercontent.com/zenml-io/zenml/main/docs/book/.gitbook/assets/zenml_logo.png
