name: text_data_report_test_pipeline
steps:
  data_loader:
    source:
      file: steps/data_loader/data_loader_step
      name: data_loader
  data_splitter:
    source:
      file: steps/data_splitter/data_splitter_step
      name: data_splitter
  text_data_report:
    source:
      file: steps/text_data_report/text_data_report_step
      name: text_data_report
  text_data_test:
    source:
      file: steps/text_data_test/text_data_test_step
      name: text_data_test
  text_analyzer:
    source:
      file: steps/text_analyzer/text_analyzer_step
      name: text_analyzer