name: kserve_tensorflow_pipeline
steps:
  importer_mnist:
    source:
      file: steps/importer_step.py
      name: importer_mnist
  normalizer:
    source:
      file: steps/normalizer.py
      name: normalizer
  tf_trainer:
    source:
      file: steps/tf_trainer.py
      name: tf_trainer
  tf_evaluator:
    source:
      file: steps/tf_evaluator.py
      name: tf_evaluator
  deployment_trigger:
    source:
      file: steps/deployment_trigger.py
      name: deployment_trigger
    parameters:
      min_accuracy: 0.8
  kserve_tensorflow_deployer:
    source:
      file: steps/model_deployer.py
      name: kserve_tensorflow_deployer
    parameters:
      model_name: "mnist"
      implementation: "tensorflow"