name: pytorch_training_deployment_pipeline
steps:
  pytorch_data_loader:
    source:
      file: steps/pytorch_steps/pytorch_data_loader.py
      name: pytorch_data_loader
      parameters:
        train_batch_size: 4
        test_batch_size: 4
  pytorch_trainer:
    source:
      file: steps/pytorch_steps/pytorch_trainer.py
      name: pytorch_trainer
      parameters:
        epochs: 3
        lr: 0.01
        momentum: 0.5
  pytorch_evaluator:
    source:
      file: steps/pytorch_steps/pytorch_evaluator.py
      name: pytorch_evaluator
  deployment_trigger:
    source:
      file: steps/deployment_trigger/deployment_trigger.py
      name: deployment_trigger
      parameters:
        min_accuracy: 0.8
  pytorch_model_deployer:
    source:
      file: steps/pytorch_steps/pytorch_model_deployer.py
      name: pytorch_model_deployer
      parameters:
        service_config: 
          model_name: "mnist"
          replicas: 1
          predictor: "pytorch"
          resources: 
            - requests: 
              - cpu:
                - 200m
              - memory:
                - 500m
        timeout: 120
        model_class_file: pytorch/mnist.py
        handler: pytorch/mnist_handler.py