---
name: Slow CI
on:
  workflow_dispatch:
  workflow_call:
  # TODO: Fix this following testing
  # issue_comment:
  #   types: [created]
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docstring-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-dind-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
      - name: Install current package as editable
        run: pip install -U darglint
      - name: Check docstrings
        run: bash scripts/docstring.sh
  small-checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.8'
      - name: Install current package as editable
        run: |
          pip install -U pip
          pip install -e .
      - name: Install mlstacks package
        run: pip install mlstacks
      - name: Check for broken dependencies
        run: pip check
      - name: Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          folder-path: ./examples, ./docs/book, ./src
          file-path: ./README.md, ./LICENSE, ./RELEASE_NOTES.md, CODE-OF-CONDUCT.md,
            CONTRIBUTING.md, CLA.md, RELEASE_NOTES.md, ROADMAP.md
          config-file: .github/workflows/markdown_check_config.json
        continue-on-error: true
      - name: Security check
        run: |
          pip install bandit
          bash scripts/check-security.sh
      - name: Check for alembic branch divergence
        env:
          ZENML_DEBUG: 0
        run: |
          pip install alembic
          bash scripts/check-alembic-branches.sh
  spellcheck:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-dind-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Spelling checker
        uses: crate-ci/typos@v1.17.0
        with:
          files: .
          config: ./.typos.toml
  update-templates-to-examples:
    # this doesn't work on forked repositories (i.e. outside contributors)
    # so we disable template updates for those PRs / branches
    if: github.event.pull_request.head.repo.full_name == 'zenml-io/zenml'
    uses: ./.github/workflows/update-templates-to-examples.yml
    with:
      python-version: '3.8'
      os: ubuntu-latest
    secrets: inherit
  custom-ubuntu-unit-test:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-dind-runners]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    uses: ./.github/workflows/unit-test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit
  windows-unit-test:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    uses: ./.github/workflows/unit-test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit
  macos-unit-test:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    uses: ./.github/workflows/unit-test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit
  windows-integration-test:
    needs: [windows-unit-test]
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        test_environment: [default]
      fail-fast: false
    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit
  macos-integration-test:
    needs: [macos-unit-test]
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        test_environment: [default]
      fail-fast: false
    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit
  custom-ubuntu-runners-integration-test:
    strategy:
      matrix:
        os: [ubuntu-dind-runners]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        test_environment:
          - default
          - docker-server-docker-orchestrator-mysql
          - docker-server-docker-orchestrator-mariadb
        exclude:
          # docker is time-consuming to run, so we only run it on 3.8
          - test_environment: docker-server-docker-orchestrator-mysql
            python-version: '3.9'
          - test_environment: docker-server-docker-orchestrator-mysql
            python-version: '3.10'
          - test_environment: docker-server-docker-orchestrator-mysql
            python-version: '3.11'
          - test_environment: docker-server-docker-orchestrator-mariadb
            python-version: '3.9'
          - test_environment: docker-server-docker-orchestrator-mariadb
            python-version: '3.10'
          - test_environment: docker-server-docker-orchestrator-mariadb
            python-version: '3.11'
      fail-fast: false
    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit
