name: Build, Lint, Unit & Integration Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "develop"]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZENML_SUPPORTED_PYTHON_VERSIONS: "['3.8', '3.9', '3.10', '3.11']"

jobs:
  configure-matrixes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set-python-versions.outputs.test }}
    steps:
      - id: set-python-versions
        run: |
          echo "test=$ZENML_SUPPORTED_PYTHON_VERSIONS" >> "$GITHUB_OUTPUT"

  ubuntu-setup-python-environment:
    needs: configure-matrixes
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  windows-setup-python-environment:
    needs: configure-matrixes
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  macos-setup-python-environment:
    needs: configure-matrixes
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  ubuntu-lint-unit-test:
    needs: 
      - configure-matrixes
      - ubuntu-setup-python-environment
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  windows-lint-unit-test:
    needs: 
      - configure-matrixes
      - windows-setup-python-environment
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  macos-lint-unit-test:
    needs: 
      - configure-matrixes
      - macos-setup-python-environment
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  ubuntu-integration-test:
    needs: 
      - configure-matrixes
      - ubuntu-lint-unit-test
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
        test_environment:
          [
            "default",
            "docker-server-docker-orchestrator",
          ]
        exclude:
          # docker is time-consuming to run, so we only run it on 3.8
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.9"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.10"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.11"

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  windows-integration-test:
    needs: 
      - configure-matrixes
      - windows-lint-unit-test
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
        test_environment: ["default"]

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  macos-integration-test:
    needs: 
      - configure-matrixes
      - macos-lint-unit-test
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
        test_environment: ["default"]

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  ubuntu-templates-test:
    needs: 
      - configure-matrixes
      - ubuntu-integration-test
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/templates-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit
  
  windows-templates-test:
    needs: 
      - configure-matrixes
      - windows-integration-test
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/templates-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  macos-templates-test:
    needs: 
      - configure-matrixes
      - macos-integration-test
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ${{ fromJSON(needs.configure-matrixes.outputs.python-version) }}
      fail-fast: false
    uses: ./.github/workflows/templates-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit
