name: Build, Lint, Unit & Integration Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main", "develop"]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ["docs/**", "docker/**", "*", "!pyproject.toml", "**.md"]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-python-environment:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  setup-python-environment-macos:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    uses: ./.github/workflows/setup-python-environment.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  lint-unit-test:
    needs: setup-python-environment
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  lint-unit-test-macos:
    needs: setup-python-environment-macos
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  integration-test:
    needs: lint-unit-test
    # Exit if its a commit from Gitbook
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        test_environment:
          [
            "default",
            "docker-server-docker-orchestrator",
          ]
        exclude:
          # docker is not supported on windows and doesn't work on macos runners yet
          - os: windows-latest
            test_environment: docker-server-docker-orchestrator
          # docker is time-consuming to run, so we only run it on 3.8
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.7"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.9"
          - test_environment: docker-server-docker-orchestrator
            python-version: "3.10"

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit

  integration-test-macos:
    needs: lint-unit-test-macos
    # Exit if its a commit from Gitbook
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        test_environment: ["default"]

      fail-fast: false

    uses: ./.github/workflows/integration-test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit
