---
name: debug-test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore: [docs/**, docker/**, '*', '!pyproject.toml', '**.md']
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: [docs/**, docker/**, '*', '!pyproject.toml', '**.md']
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mysql-db-migration-testing:
    runs-on: arc-runner-set
    env:
      ZENML_ANALYTICS_OPT_IN: false
      ZENML_DEBUG: true
    # if team member commented, not a draft, on a PR, using /fulltest
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Test migrations across versions
        run: bash scripts/test-migrations.sh mysql
