name: Kubeflow

on:
  push:
    branches:
      - feature/ENG-455-kubeflow-integration-tests

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false

    steps:
      - name: Free disk space
        run: |
          echo "Available storage:"
          df -h
          echo
          echo -n "  Removing: .NET (frees ~22GB)"
          sudo rm -rf /usr/share/dotnet
          echo "... done"
          echo -n "  Removing: Android"
          sudo rm -rf /usr/local/lib/android
          echo "... done"
          echo
          echo "Available storage:"
          df -h

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install K3D and kubectl
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Install Dependencies
        run: |
          python -m poetry install
          python -m poetry run zenml integration install kubeflow -f

      - name: Build docker image
        run: docker build -t zenml-base-image:latest -f docker/ci.Dockerfile .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Run tests
        run: python -m poetry run pytest tests/integration/test_kubeflow.py -s
