name: Post mocked events to Segment

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  schedule:
    # run this on a schedule at 5:30 in the morning every day
    - cron:  '30 5 * * *'

jobs:
  post_mocked_data:
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Post fake metadata to segment
        run: |
          python -m pip install analytics
          python scripts/mixpanel_filters_test.py