name: Publish Pypi package

on:
  workflow_call:

jobs:
  publish_to_pypi:
    name: Publish Python 🐍 package 📦 to PyPI
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: 'utf-8'

    steps:
      - uses: actions/checkout@v2

      - name: Get the version from the github tag ref
        id: get_version
        run: echo ::set-output name=VERSION::0.0.0

      # Runs a set of commands using the runners shell
      - name: publish
        env: # Or as an environment variable
#          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: ./scripts/publish.sh
