# package and push the zenml helm chart to the ECR repository
name: Publish Helm Chart

on: 
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - feature/CLOUD-289-publish-helm-chart

jobs:
  publish_to_ecr:
    name: Publish Helm Chart 🛞 to ECR ☁️
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: 'utf-8'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # add tag version to Chart.yaml file for variable version
      - name: Add tag version to Chart.yaml
        run: |
          sed -i "s/version: .*/version: \"0.43.0\"/" src/zenml/zen_server/deploy/helm/Chart.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::715803424590:role/gh-action-role-zenml-helm
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          registry-type: public

      - name: Package and push helm chart to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: q4d5e1c2
          REPOSITORY: zenml-server
        run: |
          helm package $REPOSITORY
          helm push $REPOSITORY-0.43.0.tgz oci://$REGISTRY/$REGISTRY_ALIAS