---
name: Publish Docker images
on:
  workflow_call:
    inputs:
      config_file:
        description: YAML config for Google Cloud Build
        required: false
        type: string
        default: release-cloudbuild.yaml
jobs:
  publish_to_docker:
    name: Publish Docker 🐋 image 🖼️ to Dockerhub
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Get the version from the github tag or branch
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
              # Extract the current version
              CURRENT_VERSION=$(cat src/zenml/VERSION)

              # Get the current date in the format of YYYY-MM-DD
              DATE=$(date +"%Y%m%d")

              # Combine the current version with the date to form
              # the new version string
              VERSION="${CURRENT_VERSION}.dev${DATE}"
              # Set the nightly version
              echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi
          # Sanitize the VERSION to make it Docker-compatible
          VERSION=$(echo $VERSION | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo ::set-output name=VERSION::$VERSION
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_CLOUDBUILD_EMAIL }}
          service_account_key: ${{ secrets.GCP_CLOUDBUILD_KEY }}
          project_id: ${{ secrets.GCP_CLOUDBUILD_PROJECT }}

      # Cloudbuild
      - name: Build docker images
        run: |-
          gcloud builds submit \
            --quiet \
            --config=${{ inputs.config_file }} \
            --substitutions=TAG_NAME=$VERSION
