name: Testing

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Install Dependencies
        run: |
          python -m poetry install
          python -m poetry run pip install apache-airflow~=2.2.0 gcsfs~=2021.9.0 click~=8.0.3 torch~=1.10.0
          python -m poetry run pip install awscli

      - name: Opt-out of analytics
        run: |
          python -m poetry run zenml analytics opt-out

      - name: check config 1
        run: python -c "import os; import click; from zenml import constants; from zenml.config.constants import GLOBAL_CONFIG_NAME; from zenml.utils.yaml_utils import read_json; app_dir = click.get_app_dir(constants.APP_NAME); print(read_json(os.path.join(app_dir, GLOBAL_CONFIG_NAME))['analytics_opt_in'])"

      - name: Lint
        run: python -m poetry run bash scripts/lint.sh

      - name: check config 2
        run: python -c "import os; import click; from zenml import constants; from zenml.config.constants import GLOBAL_CONFIG_NAME; from zenml.utils.yaml_utils import read_json; app_dir = click.get_app_dir(constants.APP_NAME); print(read_json(os.path.join(app_dir, GLOBAL_CONFIG_NAME))['analytics_opt_in'])"

      - name: Test
        run: python -m poetry run bash scripts/test-coverage-xml.sh

      - name: Upload coverage
        # only do it for python 3.6, we don't need to do it for every version
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2