name: Scarf checker
on:
  pull_request:
    # Run when md files are involved in the PR.
    paths:
      - '**.md'
jobs:
  check-for-scarf:
    # Only run on non-draft PRs within the same repository.
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.draft == false
    name: check-for-scarf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1

      - name: Compress Images
        run: bash .github/scripts/check-md-files.sh
