name: Spellcheck

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Use tmate session for debugging"
        required: false
        type: boolean
  workflow_call:

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"

    steps:
      - uses: actions/checkout@v2

      # Workaround from FuseML (https://github.com/fuseml/fuseml/blob/main/.github/workflows/ci.yml)
      # as the TF images are too large for the GH action runner disk
      - name: Free disk space
        run: |
          echo "Available storage:"
          df -h
          echo
          echo -n "  Removing: .NET (frees ~22GB)"
          sudo rm -rf /usr/share/dotnet
          echo "... done"
          echo -n "  Removing: Android"
          sudo rm -rf /usr/local/lib/android
          echo "... done"
          echo
          echo "Available storage:"
          df -h

      - name: Install aspell
        run: |
          sudo apt update
          sudo apt install aspell-en

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install pyspelling
        run: pip install pyspelling

      - name: Run spellcheck
        run: pyspelling
