name: Run tests on templates

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      python-version:
        description: 'Python version'
        type: string
        required: true
      enable_tmate:
        description: 'Enable tmate session for debugging'
        type: string
        required: false
        default: "never"

  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: choice
        options: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        required: false
        default: 'ubuntu-latest'
      python-version:
        description: 'Python version'
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        required: false
        default: '3.8'
      enable_tmate:
        description: 'Enable tmate session for debugging'
        type: choice
        options:
          - 'no'
          - 'on-failure'
          - 'always'
          - 'before-tests'
        required: false
        default: 'no'

jobs:
  e2e-template-tests:
    name: e2e-template-tests
    runs-on: ${{ inputs.os }}
    strategy:
        matrix:
            stack-name: [local]
        fail-fast: false
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    defaults:
      run:
        shell: bash

    steps:
      - name: run-tests-e2e-batch
        uses: zenml-io/template-e2e-batch/.github/actions/e2e_template_test@feature/OSS-2173-improve-test-action
        with:
          python-version: ${{ inputs.python-version }}
          stack-name: ${{ matrix.stack-name }}
          ref-zenml: ${{ github.ref }}
          ref-template: feature/OSS-2173-improve-test-action

      - name: message-on-error
        if: failure()
        run: |
          echo "::error title=E2E project template testing failed with new version of ZenML core!::\
            It happens then breaking changes affecting templates are introduced. To mitigate this issue,\
            please make the code in zenml-io/template-e2e-batch compatible with new version of\
            ZenML core, release it and update release tag in zenml.cli.base.ZENML_PROJECT_TEMPLATES"
  
      - name: run-tests-starter
        uses: zenml-io/zenml-project-templates/.github/actions/starter_template_test@feature/OSS-2135-add-unified-testing
        with:
          python-version: ${{ inputs.python-version }}
          stack-name: ${{ matrix.stack-name }}
          ref-zenml: ${{ github.ref }}
          ref-template: feature/OSS-2135-add-unified-testing

      - name: message-on-error
        if: failure()
        run: |
          echo "::error title=STARTER project template testing failed with new version of ZenML core!::\
            It happens then breaking changes affecting templates are introduced. To mitigate this issue,\
            please make the code in zenml-io/zenml-project-templates compatible with new version of\
            ZenML core, release it and update release tag in zenml.cli.base.ZENML_PROJECT_TEMPLATES"
