name: Run tests on templates

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      python-version:
        description: 'Python version'
        type: string
        required: true
      enable_tmate:
        description: 'Enable tmate session for debugging'
        type: string
        required: false
        default: "never"

  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: choice
        options: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        required: false
        default: 'ubuntu-latest'
      python-version:
        description: 'Python version'
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        required: false
        default: '3.8'
      enable_tmate:
        description: 'Enable tmate session for debugging'
        type: choice
        options:
          - 'no'
          - 'on-failure'
          - 'always'
          - 'before-tests'
        required: false
        default: 'no'

jobs:
  get-matrix-of-templates:
    runs-on: ${{ inputs.os }}
    outputs:
      matrix: ${{ steps.et-matrix-of-templates.outputs.matrix }}
    steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ inputs.python-version }}

        - name: set-matrix-of-templates
          id: set-matrix-of-templates
          run: echo "::set-output name=matrix::$(python3 ./scripts/template-matrix.py) generate"

  templates-tests:
    name: templates-tests
    needs: get-matrix-of-templates
    runs-on: ${{ inputs.os }}
    strategy:
        matrix:
            template: ${{ fromJson(needs.get-matrix-of-templates.outputs.matrix) }}
        fail-fast: false
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"
      # on MAC OS, we need to set this environment variable
      # to fix problems with the fork() calls (see this thread
      # for more information: http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html)
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
    # Exit if it's a commit from Gitbook
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python-version: ${{ inputs.python-version }}
          os: ${{ inputs.os }}
      
      - name: set-matrix-of-templates
        id: set-matrix-of-templates
        run: echo "::set-output name=matrix::$(python3 ./scripts/template-matrix.py) parse '${{ matrix.template }}'"

      # - name: Setup tmate session before tests
      #   if: ${{ inputs.enable_tmate == 'before-tests' }}
      #   uses: mxschmitt/action-tmate@v3

      # - name: Run unit tests
      #   run: |
      #     bash scripts/test-templates.sh

      # - name: Setup tmate session after tests
      #   if: ${{ inputs.enable_tmate == 'always' || (inputs.enable_tmate == 'on-failure' && failure()) }}
      #   uses: mxschmitt/action-tmate@v3

      # - name: Verify Python Env unaffected
      #   run: |
      #     zenml integration list
      #     pip list
      #     pip check || true
