name: Auto-update E2E template

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      python-version:
        description: 'Python version'
        type: string
        required: true

  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: choice
        options: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        required: false
        default: 'ubuntu-latest'
      python-version:
        description: 'Python version'
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        required: false
        default: '3.8'

jobs:
  update-template:
    name: update-template
    runs-on: ${{ inputs.os }}
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      # - name: Setup environment
      #   uses: ./.github/actions/setup_environment
      #   with:
      #     cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
      #     python-version: ${{ inputs.python-version }}
      #     os: ${{ inputs.os }}

      # - name: Check-out fresh E2E template
      #   run: |
      #     mkdir -p examples/e2e
      #     printf 'info@zenml.io' | zenml init --path examples/e2e --template e2e_batch --template-with-defaults
      
      - name: Fake changes
        run: |
          touch fake_change.txt
      - name: Check for changes
        run: |
          if git diff --quiet HEAD^..HEAD; then
            echo "No active Git changes found."
            echo "::set-output name=changes::false"
          else
            echo "Active Git changes found."
            echo "::set-output name=changes::true"
          fi
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^..HEAD; then
            echo "No active Git changes found."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Active Git changes found."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push template
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update of template"
          git push origin HEAD:${{ github.ref }}

      - name: Create PR comment
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Auto-update of template changes have been pushed.'
            })


